export const aboutMoveText = {
  umMyndinaC: 'Um Myndina: Chronicle',
  cTexsti: 'Myndin Chronicle fjallar um þrjá stráka sem enda með að finna einhvers konar ofurkrafta frá óþekktum aðferðum. Við horfum á strákana í gegnum myndavélar og þar aðallega í gegnum myndavél hans Andrew Detmer sem er að taka allt upp af einhverjum ástæðum. Strákarnir Andrew, Matt, Steve byrjað að mynda vinasamband þar sem þeir skoða nýju máta sína og hjálpa hvor öðrum að nota þá og að bestu getu. Andrew endar þó með því að trúa að hann sé betri en aðrir og endar með að drepa Steve óvart þegar hann var að reyna hjálpa honum. Eftir dauða Steve þá brotnar samband Andrews og Matts niður þar sem Andrew fer að trú að hann sé einhver skonar guð. Þetta endar allt með að Andrew fer og drepur pabba sinn sem var búin að vera ofbeldis fullur gegn honum en Matt vil ekki að Andrew geri það þannig þeir berjast sem endar með dauða Andrews.',
  cÖðruvísiTitil: 'Hvernig eru hún öðruvísi',
  cÖðruvísi: 'Þegar við hugsum um hvernig Chronicle er öðruvísi ofurhetju mynd þá er stærsta atriðið hvernig við erum að horfa í gegnum myndavélar sem eru að taka upp allt sem er að gerast. Þetta hefur þó verið gert í öðrum myndum eins og the blair witch project en ekki oft í ofurhetju myndum. Líka ofurkraftar þeirra og hvernig þeir fá það yfirlegt er gert stórt atriði um hvernig ofurhetjan fær krafta sína en ekki í Chronicle. Atriðið þar sem þeir fá krafta sína er mjög stutt og lítið útskýrt þar sem þeir finna bara stein og eru með krafta eftir það. Annað er endirinn og hvernig Andrew verður sá vondi eða antihero eins og sumir mundu segja þar. Myndin er ekki þessi hefðbundna ofurhetjumynd eins og við munum sjá frá Marvel og við fáum góða tilfinningu fyrir því út frá hvernig myndin er í sjónarhorni frá myndavélum.',
  
  
  umMyndinaU: 'Um Myndina: Unbreakable',
  uTexsti: 'Myndin Unbreakable er um David Dunn sem með fyrstu sýn er venjulegur öryggisvörður en þegar hann lendir í lestarslysi þar sem allir nema hann deyja fer hann að velta fyrir sér hvort hann sé með ofurkrafta. Elijah Price sem er mikið fyrir ofurhetjublöð hittir David og þeir fara skoða máta hans saman þar sem Elijah sér að David er með einhverskonar sjónarkrafta þar sem hann sér fram fyrir hættu áður en hún á sér stað. David fer líka að lyfta 200+ kílóum og fer virkilega að trúa að hann sér með ofurkrafta. Elijah hjálpar David að gera sig að ofurhetju þar sem hann fer í regnjakka og hjálpar fólki sem var búið að taka í gíslingu heima hjá sér. David endar með að hjálpa þeim og það er frétt skrifuð um hann en þegar allt virðist vera gott kemur Elijah fram og segir að hann er búina að vera filgast með David og vissi allt um hann áður fyrr og það hefði verið hann sem valdi öllum þessum slysum til að skoða hvort David var trúlega ódauðlegur.',
  uÖðruvísiTitil: 'Hvernig eru hún öðruvísi:',
  uÖðruvísi: 'Unbreakable er mjög áhugaverð mynd út frá því að við fylgjumst með ofurhetju sem er með rosalega krafta sem veit ekki af því. Í öllum ofurhetju myndum sem ég hef séð þá veit aðalpersónan að þeir séu með krafta að einhverju magni en í Unbreakable þá erum við að fylgjast með David sem er fullorðinn maður sem fæddist með ofurkrafta og veit ekki af því. David er með hann kraft að hann meiðist ekki David hefur aldrei orðið veikur eða brotið bein og er mjög sterkur en hefur ekkert spáð í því. Þetta dæmi um að ofurhetjan viti ekki að kröftum sínum er eitthvað sem er ekki oft notað.',   
  
  
  umMyndinaW: 'Um Myndina: Super',
  sTexsti: 'Myndin Super fjallar um hann Frank Darbo sem er hefðbundin maður sem er giftur henni Sarah en samband þeir er á vondum stað þar sem Sara er fyrrverandi fíkil og hættir með Frank til að byrja með öðrum. Frank tekur þessu ekki vel og lofar að ná henni úr fíkniefnaheiminum og neyslu. Þegar Frank er á hóteli eftir að það var búið að ráðast á hann þegar hann reyndi að ná Sarah til baka þá fær hann kall frá guð sem segir honum að verða ofurhetja. Eftir þetta guðlega skilaboð býr Frank til búning og fer út að berjast við glæp á sínum forsendum. Frank klæðist rauðum búning og notar skiftilikil til að berjast á móti voldum illu. Frank hittir Libby í myndasöguverslun og hún endar með að aðstoða hann í bardaga við ofl það illa. Myndin endar með stóra árás á hús þar sem Sarah er að njóta við eiturlyf þannig Frank og Libby fara þangað vel vopnuð með sprengjur og bussur til að ná henni út. Libby endar með að deyja og Frank finnur Sara og drepur nýja kærasta hennar til að stoppa ílsku. Frank og Sarah fara saman út en byrja ekki saman þrátt fyrir allt.',
  sÖðruvísiTitil: 'Hvernig eru hún öðruvísi:',
  sÖðruvísi: 'Super er mjög áhugaverð mynd og það er þó nokkuð eftir að útskýra hana nema bara segja viðkomanda að horfa á myndina. Til að reyna þá má segja að Super gerir grín að því hvernig ofurhetjur ákveða hvað er rétt og hvað er ránt. Dæmi í myndini er þegar Frank er að fara í bíó og hjón fara fram úr í röð sem sem endar með að Frank fer í búning og réðst á fólki með skiftilikil. Fyrir Frank þá eru allir glæpir jafn stórir þar sem hann beitir skiptilykli sínum á dópsala og einhvern sem fer fram úr röð. Annað dæmi er í myndin þar sem Libby sem er að aðstoða Frank nauðgar honum sem er eitthvað sem bara gerist varla í bíómyndum.',   
    
    
  umMyndinaW: 'Um Myndina: Watchmen',
  wTexsti: 'Watchmen myndin fjallar um allskonar ofurhetjur sem hafa enga krafta og eru nú banaðar af lögum að starfa nú til dags. Dr. Manhattan er ofurhetja sem er ekki eins og hinir þar sem hann er nærum guð sem getur gert allt sem hann vil eftir að hafa lenti í einhverskonar rafmaks slysi. Myndin fjallar um hvernig ofurhetjunar eru dregnar aftur í hetju bransan þar sem fyrrverandi hetjan Adrian planar að bjarga heiminum með því að sameina hann gegn Dr. Manhattan. Adrian sem er sagður vera gáfasti maður í heiminum nær þessu með því að spengja stórborgir og láta það líta eins og Manhattan hafi gert það sem sameinar Bandaríkin og Sovétríki til að finna lausn á frið. Myndin endar með því að Manhattan tekur við sökini og flýr frá jörðinni og allar hetjunar segja engum um sannleikan til að halda friðinum nema Rorschach sem er drepinn.',
  wÖðruvísiTitil: 'Hvernig eru hún öðruvísi:',
  wÖðruvísi: 'Watchmen er ekki þessi venjulega Marval eða DC mynd en samt ekki eins öðruvísi og hinar myndirnar. Í Watchmen þá eru engin nema Dr. Manhattan sem er með ofurkrafta og það sem stendur út við það er að  Dr. Manhattan er nærum guð sem getur gert allt. Hinnar ofurhetjunar eru líkar batman þar sem þær nota búnað og gáfur til að berjast við það illa. Endirinn er líka þó nokkuð óhefðbundinn þar sem vondi er ekki stopaður og drepur milljónir og allir nema Rorschach eru bara sammála honum að halda leyndarmálinu líka. Dr. Manhattan sem getur gert hvað sem er hvenær sem er endar með því að vera sammála og fer bara sem er smá skrítið þegar þú hugsar út í hann getur gert hvað sem er til dæmis komið fyrir frið á jörðu en hann gleymir að spá í því held ég.',  
  // byrjun
  hvaðErPóstmódernism: 'Póstmódernismi er hugtak sem kom upp eftir seinni heimsstyrjöldina og nýlega hefur hugtakið verið á uppleið þar sem nútíma listamenn fara að nota það. Aðal skilgreining á póstmódernismi er gagnrýnir á hefðbundinni skilgreiningu á sannleika, þjóðfélagi, og menningu þetta sést í listaverkum og nýlega í allskonar kvikmyndum. Tilgangur póstmódernismi er að brjóta það hefðbundna stíl og búa til nýjan sem blandar allskonar efnum og menningarþáttum saman til að búa til eitthvað nýtt. Póstmódernismi hefur haft áhrif á margvísleg svið þar á meðal listir, menningarfræði, stjórnmál, og samfélagsvísindi, og hefur valdið margvíslegum rökræðugreinum um merkingu og áhrif menningarinnar í samtíma.',
  póstmódernismiKvikmyndum: 'Postmodernismi í kvikmyndum endurspeglar gagnrýni á hefðbundnum kvikmyndakenningum. Stærsta einkenni þessar stefnu er truflun á gagnsæi þar sem raunveruleiki og fiktion blanda saman. Intertextuality er algengt með vísbendingum, tilvitnanir og tengingum við önnur verk sem skapar alls konar merkingar. Viðmiðunar Frelsi og fjölbreytileiki er stór partur af því sem póstmodernistar leika sér með. Gagnrýni á stórar fortællingar er einnig augljós og póstmodernistar skapa nýjar upplifanir með því að brota við hefðbundnum ævintýrum. Þáttafræði og skilvirkni eru áberandi með áherslu á áhrif myndarinnar á áhorfendur og gagnrýni á merkingu orða og mynda. Dæmi um póstmódernískar kvikmyndir eins og Pulp Fiction eða The Matrix leika sér með þessi einkenni og skapa nýjar og oft óvæntar myndatengingar.',
  útskýraOfurhetjumyndir: 'Ofurhetjumyndir fjalla um einstaklinga sem eiga eftir að standa fram og berjast fyrir réttlæti og lög og reglum. Ofurhetjumyndir einkennast af sérstökum einstaklingum sem eiga einhvern ofurkraft sem réttlætir þeim að taka réttarhöld í sínar eigin hendur og stopa hitt illa. Það er þó ekki alltaf hetja sem getur haldið á lest eða tekið til lofts heldur getur það verið hver sem er. Ofurhetjumyndir falla undir ákveðið snið þar sem lagt er áherslu á mikinn spennuþátt, myndatöku og sérhæfða ástarstiga milli góðra og slæmra. Þær myndir geta einnig innifalið gagnrýni á samfélagið, innifelt persónuleikaþroska einstaklingsins og sýnt hvernig hann eða hún takast á við erfiðleika. Hugtök eins og "origin story" (frásagnir um uppruna) og "character arc" (þroskaskeið persónu) eru algeng í uppbyggingu ofurhetjumynda. Meðalveran getur verið í að einstaklingurinn eða einstaklingarnir fái að sýna hvernig þau þroskast og breytast eftir áhöfn og atburði.',
  ÚtskýraPóstmódernískarOfurhetjumyndir: 'Póstmódernískar ofurhetjumyndir einkennist af gagnrýni á hefðbundnum hetjusöguþráð og er sérstaklega áhæsla á flóknar persónur eða brotlegar persónuleikur. Myndir sem flokkast undir póstmódernískar blanda saman alkonar stílum, tímum eða menningarþáttum til að búa til öðruvísi söguþræði. Áhersla á persónuleikaþroska er mjög sjáanleg í póstmódernískum ofurhetju myndum sem er ekki eins augljóst í hefðbundnum ofurhetju myndum þar sem aðalpersónan er alltaf sú góða að berjast við það illa. Þessi hefðbundna hugmynd um gott og illt er ekki svart-hvít þú getur fundið tengjast með því sem talið er vera illt og sýnt samkennd þar. Annað sem þessar myndir gera er að draga af hefðbundnum hetjusögum og gagnrýna eða snúa upp og niður yfir hefðbundnar áætlanir um sannleika, réttlæti og eðli góðra og slæmra. Nokkrar stórar póstmódernískar ofurhetjumyndir eru Deadpool, Watchmen, Chronicle, Unbreakable, Super.',
}

